config/routes.rb
Rails.application.routes.draw do
  resources :three_d_secure_subscriptions, only: [:new, :create]

  resources :donates, only: [] do
    collection do
      get :show
      get :thankyou
    end
  end

  resource :purchases, only: :create

  # mount StripeEvent::Engine, at: '/stripe/webhook'
  post "/stripe/webhook", to: "stripe_webhooks#event"

  resources :products

  devise_for :users

  resources :subscriptions, only: [:new, :create] do
    scope module: 'subscriptions' do
      collection do
        resource :unsubscribe, only: :destroy
        resource :resubscribe, only: :new
      end
    end
  end

  root to: 'home#index'
  get '/example', to: 'home#example'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def example
    render json: { message: 'Exemplo de resposta AJAX' }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<% if current_user&.subscribed? %>
  SUBSCRIBED - <%= current_user.stripe_subscription_id %><br>
  <%= button_to "Cancel Subscription", unsubscribe_path,
              data: { confirm: "Are you sure?" }, class: 'btn btn-primary',
              method: :delete unless current_user.expires_at %>
  <%= link_to "Resubscribe", new_resubscribe_path, class: 'btn btn-primary' if current_user.expires_at %>
<% else %>
  <p><%= link_to "Subscribe Now!", new_subscription_path, class: 'btn btn-primary' %></p>
<% end %>

<hr>

<%= link_to "Donate", "https://donate.stripe.com/test_eVa8xn2URcIXfeM288", target: :_blank %> |
<%= link_to "Donate $5", donates_path(amount: 500) %> |
<%= link_to "Donate $50 ", donates_path(amount: 5000) %>

<%= form_with url: donates_path, "data-turbo": false, method: :get do |f| %>
  <%= f.number_field :amount %>
  <%= f.submit "Donate" %>
<% end %>

<hr>

<% if user_signed_in? %>
  <p><%= link_to 'Subscribe to Premium for $50/month', new_three_d_secure_subscription_path, class: 'btn btn-primary' %></p>
<% end %>