config/routes.rb
Rails.application.routes.draw do
  resources :three_d_secure_subscriptions, only: [:new, :create]

  resources :donates, only: [] do
    collection do
      get :show
      get :thankyou
    end
  end

  resource :purchases, only: :create

  # mount StripeEvent::Engine, at: '/stripe/webhook'
  post "/stripe/webhook", to: "stripe_webhooks#event"

  resources :products

  devise_for :users

  resources :subscriptions, only: [:new, :create] do
    scope module: 'subscriptions' do
      collection do
        resource :unsubscribe, only: :destroy
        resource :resubscribe, only: :new
      end
    end
  end

  root to: 'home#index'
  get '/example', to: 'home#example'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/subscriptions/resubscribes_controller.rb
# controllers/subscriptions/resubscribes_controller.rb
module Subscriptions
  class ResubscribesController < ApplicationController

    def new
      subscription = Stripe::Subscription.list(customer: current_user.stripe_id).first
      if subscription.save
        current_user.update(stripe_subscription_id: subscription.id, expires_at: nil)
        flash.notice = "Thanks for resubscribing!"
      else
        flash.alert = "There was a problem resubscribing!"
      end
      redirect_to root_path
    end
  end
end

app/controllers/subscriptions/unsubscribes_controller.rb
module Subscriptions
  class UnsubscribesController < ApplicationController
    def destroy
      subscription = Stripe::Subscription.update(current_user.stripe_subscription_id, {cancel_at_period_end: true})
      expires_at = Time.at(subscription.current_period_end)
      current_user.update(stripe_subscription_id: nil, expires_at: expires_at)
      redirect_to root_path, notice: "You have cancelled your subscription.
      You will have access until #{l current_user.expires_at.to_date, format: :long}."
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    customer = current_user.stripe_customer
    begin
      subscription = Stripe::Subscription.create({
                                             customer: customer.id,
                                             items: [{plan: "plan_OB8cm9kBaZcPCb"}],
                                             payment_settings: {payment_method_types: ['card']}
                                           })
      current_user.assign_attributes(stripe_subscription_id: subscription.id)
      current_user.save
      redirect_to root_path, notice: 'Thanks for subscribing!'
    rescue Stripe::CardError => e
      flash.alert = e.message
      render action: :new
    end
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/create.html.erb
<h1>Subscriptions#create</h1>
<p>Find me in app/views/subscriptions/create.html.erb</p>

app/views/subscriptions/new.html.erb
<h1>Subscriptions#new</h1>
<p>Find me in app/views/subscriptions/new.html.erb</p>

<div class='row'>
  <div class='col-md-3'></div>
  <div class='col-md-6'>
    <!-- STRIPE FORM HERE -->
    <%= form_with url: subscriptions_path, method: :post, id: 'payment-form' do |form| %>
      <div class="form-row">
        <label for="card-element">Credit or debit card</label>
        <div id="card-element"></div>
        <div id="card-errors" role="alert"></div>
      </div>
      <%= form.submit 'Subscribe', class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div class='col-md-3'></div>
</div>